### ISSUE TITLE
3.4.1 blender does not install

### ISSUE THREAD

**Issue by xintoc** [Rokoko/rokoko-studio-live-blender#105]
does not work with pip version 23.0. fails at update pip

**Comment by AlphaRed231** [comment]
Not sure if this is the same issue. Plug in failed to load. Blender 3.4.1


![Rokoko Blender Plugin error](https://user-images.githubusercontent.com/125930379/220211966-32be27eb-a9f8-4ddd-9ebd-5d2e82a81c64.png)

**Comment by Arkitect-z** [comment]
这个错误是没有C盘的读写权限，我用管理员身份重新打开Blender后安装成功了

**Comment by Darkblader24** [comment]
Hey, please try starting Blender as an admin and try again. Also you can give the beta version of the plugin a try, you get better error messages there.
