### ISSUE TITLE
cannot install plugin

### ISSUE THREAD

**Issue by Karnor** [Rokoko/rokoko-studio-live-blender#108]
I get this error
```
import ensurepip
ModuleNotFoundError: No module names `ensurepip`

```
But when I try to install ensurepip on my system I get told there is no such module

```
$ python3 -m ensurepip
/usr/bin/python3: No module named ensurepip

```
How do people use this plugin on Ubuntu or do they just delete their system and install a different less anal linux distro?

**Comment by Karnor** [comment]
Any answer to this?

**Comment by Darkblader24** [comment]
Make sure Blender uses the bundled Python environment it comes with instead of the locally installed Python environment. Let me know if this fixed it for you.
