### ISSUE TITLE
Remove Login?

### ISSUE THREAD

**Issue by NHodgesVFX** [Rokoko/rokoko-studio-live-blender#43]
What is the point of having a login in the plugin? Verification for plus and pro features should take place in Rokoko studio. If that is already the case why have the login in the plugin? All it does is require you unnecessarily to create a Rokoko account, add code complexity and add an additional reliance on Rokoko servers.

I already use rokoko studio and have an account, however it would be beneficial to all users to remove the login. Since there are no other free plugins for re-targeting I can see this gaining traction for users who want to use mocap from any source. Including Rokoko. Forcing a user to create an account, for seemingly no benefit, will only serve as a deterrence and a annoyance. 

Thanks for taking this into consideration :)

**Comment by stryker313** [comment]
I would second this. Rokoko logins also have been a little buggy, as it would log me out of my account, and then say I have to sign in again. The description reads "sign in is required once", but if I have to do it multiple times, isn't this counterintuitive?

**Comment by Darkblader24** [comment]
Unfortunately we won't remove the login, be we have reworked it to make it much easier to use!

**Comment by CountPepperoni** [comment]
Personally, I fail to see why an account is even needed for something as simple as a blender plugin. The only reason I can see is that you want to integrate people into your ecosystem and collect personal data. Disappointing, and I'll be sure to delete my account once I find a functional alternative for retargetting animations.
