### ISSUE TITLE
Plugin not working on linux / mac

### ISSUE THREAD

**Issue by Seb-Perso** [Rokoko/rokoko-studio-live-blender#45]
Hi !

I think some of your python code is windows specific, any way to change that by any chance ? ;)

I get this when trying to install the plugin :

  File "/home/seb/bin/blender/2.83/python/lib/python3.7/ctypes/wintypes.py", line 20, in <module>
    class VARIANT_BOOL(ctypes._SimpleCData):
ValueError: _type_ 'v' not supported

Thanks,

Sébastien

**Comment by Seb-Perso** [comment]
Seems to work with the master version !

**Comment by Seb-Perso** [comment]
Sorry yes there are missing features in the master version (retargeting in particular) so I guess this is still active.

**Comment by Darkblader24** [comment]
Yes, version 1.1 is still in beta. It will be fully released once it works on Mac and Linux.

**Comment by Seb-Perso** [comment]
Noted, thanks for the feedback ! ;)

**Comment by Darkblader24** [comment]
The update is released, it should work now on Linux and Mac
