### ISSUE TITLE
Plugin v1.1.0 doesn't load on macOS

### ISSUE THREAD

**Issue by aka-anoop** [Rokoko/rokoko-studio-live-blender#47]
OS: macOS Catalina 10.15.6
Blender: 2.83.3
Plugin version: 1.1.0
The plugin installed fine, but it just doesn't load and crashes with following traceback.

![Screenshot 2020-07-30 at 4 47 06 PM](https://user-images.githubusercontent.com/4973393/88917169-efdd5f80-d284-11ea-9bda-4be648a7aa5b.png)

However, the version 1.0.0 loads fine. But I wanted to checkout the Blender mocap retargeting features.

**Comment by Darkblader24** [comment]
Support for Mac and Linux will be added in the full update. It will be released very soon.

**Comment by Darkblader24** [comment]
The update is released, it should work now on macOS

**Comment by aka-anoop** [comment]
Thank you. on it!
