### ISSUE TITLE
Latest release (1.2.0) raises error when attempting to install

### ISSUE THREAD

**Issue by DavidLSmyth** [Rokoko/rokoko-studio-live-blender#60]
When attempting to enable on windows 10, blender 2.83, I'm met with the following error: 

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'rokoko-studio-live-blender-1'

**Comment by trajesus** [comment]
I'm having the same issue, but within blender 2.90.1

**Comment by DavidLSmyth** [comment]
unzip, rename the unzipped folder to rokoko-studio-live-blender and then zip as rokoko-studio-live-blender.zip. Install this file to Blender and the problem goes away for me

**Comment by trajesus** [comment]
Worked for me too, thank you

**Comment by Darkblader24** [comment]
Thanks for the report! New downloads won't have this issue anymore.

**Comment by amir-abbas462** [comment]
what should i do with this error?
i tried unzipping renaming and re-zipping but it didn't work.
![rokoko](https://user-images.githubusercontent.com/83920717/117582435-3a92de80-b117-11eb-9178-b55462f90f61.png)

**Comment by sanskarbiswal** [comment]
I faced the exact same issue. Rezipping did not solve the error either. This issue arises when I moved to Blender 2.93

**Comment by lemonteapk** [comment]
me too, maybe it hasn't been made for blender 2.93, this error should be fixed soon

**Comment by ryanmartinson1992** [comment]
I had the error as amir-abbas462 unzipping, renaming, and rezipping has not worked. Does anyone know how to get this add-on to install?
