### ISSUE TITLE
Not logging in with mac 10.13.6

### ISSUE THREAD

**Issue by RichardEllicott** [Rokoko/rokoko-studio-live-blender#70]
Hi

I get an error saying a file libcurl.dylib is built for OS X 10.15

is it the case that authorisation is not supported with mac OS 10.13.6 ?

**Comment by winniejo** [comment]
Its always the same problem when will people/companies get that 
a lot are running MacOs10.9 to 10.12 also for good reasons.

**Comment by RichardEllicott** [comment]
well it's their loss

for my own problem i found godot-game-tools. i was just looking for something that could import the mixamo animations to blender, godot-game-tools you can select all the animation files at once and just load them in batch

**Comment by winniejo** [comment]
Great !! 
Found out you can import different animations in Blender and combine/tweek them also.

Thanks and keep it up! :)

**Comment by Darkblader24** [comment]
The latest plugin version now supports older Mac versions as well!
