### ISSUE TITLE
Remove The Sign In/Log In?

### ISSUE THREAD

**Issue by stryker313** [Rokoko/rokoko-studio-live-blender#74]
Rokoko logins also have been a little buggy, as it would log me out of my account, and then say I have to sign in again. The description reads "sign in is required once", but if I have to do it multiple times, isn't this counterintuitive?

This may be a hassle for new users, its such a weird blockade.

It would make sense if Rokoko removed the login, especially for users who just want to use something like the retargeted.

**Comment by Darkblader24** [comment]
Unfortunetely we won't remove the login, but we reworked it and it is much easier to use now!
