### ISSUE TITLE
Error when attempting to enable 

### ISSUE THREAD

**Issue by Florian-crg** [Rokoko/rokoko-studio-live-blender#79]
Impossible to enable rokoko on blender 2.93.

https://github.com/Rokoko/rokoko-studio-live-blender/issues/60

<img width="1006" alt="Capture d’écran 2021-11-24 à 23 08 59" src="https://user-images.githubusercontent.com/20863963/143318944-a8f79fbb-8c63-41f7-93a6-3f7c0780f417.png">

**Comment by Darkblader24** [comment]
This has been fixed in v1.14!
