### ISSUE TITLE
Can't Sign in (even after creating an account)

### ISSUE THREAD

**Issue by AmanosamaCiel** [Rokoko/rokoko-studio-live-blender#81]
I've created an account and verified it but when i try to sign in using the ID and PAssword of my acocunt, it says that one of them is wrong but when i do it on the website, it works. How can fix this ?

**Comment by Winebread** [comment]
Same problem.

**Comment by agentasteriski** [comment]
Me too.

**Comment by AmethS** [comment]
Same problem +1

**Comment by morzh** [comment]
and me

**Comment by Darkblader24** [comment]
Hey everyone, this issue is now fixed. Please try again using the beta version: https://github.com/Rokoko/rokoko-studio-live-blender/archive/refs/heads/beta.zip
