### ISSUE TITLE
Problem streaming data from Rokoko to Blender

### ISSUE THREAD

**Issue by B-Skizzle** [Rokoko/rokoko-studio-live-blender#91]
I'm not sure what's going on here so I'm going to give you as much information as possible, but long story short, Rokoko can connect to Blender via the plugin, but no data is appearing in Blender.

I have version 3.0 of Blender:
![image](https://user-images.githubusercontent.com/92380380/168446542-32dd667d-80f4-4f67-a55b-b165356efe43.png)

The plugin version is 1.4.0:
![Capture](https://user-images.githubusercontent.com/92380380/168446499-8c9aa8f8-bd61-4eee-b20f-8fefbd02d68e.JPG)

These next two images show that Rokoko is live streaming to Blender:
![image](https://user-images.githubusercontent.com/92380380/168446573-a6e897c6-a18d-4c21-9595-158dd558d054.png)

![image](https://user-images.githubusercontent.com/92380380/168446585-ef60b94c-eff5-4296-a6e3-730a394a7c9c.png)

This image shows that the plugin is connecting to Rokoko, but I'm not getting any suit information under the "Starting Recording" button (I'm assuming this should pop up after connecting to the Rokoko software, based on the YouTube tutorials on how this should work).  The "Rokoko Studio Live Setup" panel in the object properties tab of my armature is also saying there's no prop/actor data available. 

![image](https://user-images.githubusercontent.com/92380380/168446627-dc1f0ebc-d2b8-4c01-8c59-659c2ab1e039.png)

Lastly, this is what is being displayed on the system console in Blender:

![image](https://user-images.githubusercontent.com/92380380/168446660-521e1805-e850-48e5-b27e-c4716c35b096.png)

Let me know if you need any more information.  I've tried various versions of Blender (3.1, 3.0, 2.93) and I'm still having the same issues.

**Comment by B-Skizzle** [comment]
Whoops.  Looks like I forgot to select a actor profile in Rokoko.  It works now.

**Comment by Darkblader24** [comment]
Glad you got it working. I think I can add a small notification if this happens
