### ISSUE TITLE
Rokoko Blender Live Streaming Performance Lag

### ISSUE THREAD

**Issue by B-Skizzle** [Rokoko/rokoko-studio-live-blender#93]
This is more of a question than an issue. I know that the plugin has the ability to disable meshes to increase performance, but I noticed that for my particular purposes (using Blender's virtual reality feature to act out character movements while emboding that character), even when the character's mesh is disabled, the armature still lags to to copy what rokoko does.  I figure it's because of the virtual reality feature, but do you know if there are any more optimizations that could be made to the plugin?

**Comment by Darkblader24** [comment]
By lagging do you mean actual laggy animations or do you mean the delay between your movement and the armature moving?
If you talk about about the delay, then you should be able to reduce it by choosing a JSON format without LZ4. You can do this by choosing the "Custom" live streaming option in Studio and changing the API there.

**Comment by B-Skizzle** [comment]
I mean the delay between my movement and the armature moving. 

To choose a JSON format without LZ4, I can use the legacy studio, right?

**Comment by Darkblader24** [comment]
Yes, both Studio versions 1 and 2 are compatible

**Comment by B-Skizzle** [comment]
Thank you! It sped up the performance by a lot.

**Comment by Darkblader24** [comment]
This is great! Could you give me an estimate of what the delay was before and what it is now?
I think it's worth to make the non LZ4 protocol the default.

**Comment by B-Skizzle** [comment]
It had a delay of 1.5 seconds and then it dropped down to less than .5 seconds.  It may seem small, but in VR that delay is enough to throw me off.

**Comment by Darkblader24** [comment]
Yes, one second makes a huge difference when using VR. Thank you very much for letting me know!
