### ISSUE TITLE
Source selection not working in retargeting

### ISSUE THREAD

**Issue by archeryprogrammer13** [Rokoko/rokoko-studio-live-blender#97]
Trying to do retargeting, but when I try selecting a source, nothing comes up. If I try to use the eyedropper tool, it fails to register any of the armatures -- or any other objects, at that -- in the scene. If I try typing in the name of the armature I want to select as the source, the name simply disappears as soon as I press enter or left click. The target selection box works completely fine.

**Comment by Darkblader24** [comment]
Hey! The source armature is required to have an animation attached to it, otherwise the retargeting wouldn't make sense.

**Comment by archeryprogrammer13** [comment]
Yeah, it does have an animation on it. comes up as selectable for targeting though.
Maybe there's something weird going on with the animation...

**Comment by archeryprogrammer13** [comment]
None of the bones have keyframes... interesting...

**Comment by archeryprogrammer13** [comment]
Yayy I got it working

**Comment by plugcrypt** [comment]
It's always nice to see people asking for help and not saying how they fixed their stuff.
